name: Build Application

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'
          cache: true

      - name: Build
        run: |
          go build -o geoip-reader \
          -ldflags="-X main.Version=${{ github.ref_name }} \
            -X main.BuildTime=$(date -u '+%Y-%m-%d_%H:%M:%S') \
            -X main.Commit=${{ github.sha }}" \
          .

      - name: Upload binary to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: geoip-reader-linux-amd64
          path: geoip-reader
          if-no-files-found: error

      - name: Publish to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: release-binary
          path: geoip-reader